#!/usr/bin/env bash

set -e

DIR="$( dirname -- "${BASH_SOURCE[0]}"; )"; # Get the directory name
CURRDIR="$( realpath -e -- "$DIR"; )"; # Resolve its full path if need be

source "${CURRDIR}/utils.sh"
source "${CURRDIR}/vim-plugin-list.sh"

"${CURRDIR}/install-plugins"

for plugin in ${NICE_TO_HAVES[@]}; do
  install_plugin "$plugin"
done
