#!/usr/bin/env bash

set -e

DIR="$( dirname -- "${BASH_SOURCE[0]}"; )"; # Get the directory name
CURRDIR="$( realpath -e -- "$DIR"; )"; # Resolve its full path if need be

source "${CURRDIR}/utils.sh"
source "${CURRDIR}/vim-plugin-list.sh"

echo "
This script allows you to install some plugins temporarily, for
example during a pairing session.
echo
It will:
- clone the plugins from github...
- ...under ~/.vim/pack/bundle/start with a name 'bouncing-vim-tmp-<plugin>'
- skip the plugins the are already installed

This is the list of plugins:
"

for plugin in ${ESSENTIALS[@]}; do
  echo "  - ${plugin}"
done

echo
echo "Do you want to proceed?"
read -r
if [[ ! $REPLY =~ ^[Yy] ]]; then
  echo "Aborting as requested."
  exit 1
fi

for plugin in ${ESSENTIALS[@]}; do
  install_tmp_plugin "${plugin}"
done
